#! -*- coding:utf-8 -*-


import datetime
import re
import time

import pymysql
import requests
from lxml import etree
from requests.exceptions import RequestException

def call_page(url):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            return response.text
        return None
    except RequestException:
        return None

# 正则和lxml混用
def parse_html(html):  # 正则专门有反爬虫的布局设置，不适合爬取表格化数据！



    selector = etree.HTML(html)
    Price = selector.xpath('//*[@id="spFP"]/div[1]/span[1]/text()')
    MV = selector.xpath('//*[@id="hqpanel"]/div[2]/div[3]/ul[2]/li[4]/span[2]/text()')
    for item in  MV:
        f_=item[:-1]
        mv_l.append(float(f_))


    for i1,i2 in zip(Price,MV):
        sum_mv = sum(mv_l)
        count_l.append(float(i1)*(float(i2[:-1])/float(sum_mv)))






def RemoveDot(item):
    f_l = []
    for it in item:

        f_str = "".join(it.split(","))
        f_l.append(f_str)

    return f_l




def remove_block(items):
    new_items = []
    for it in items:
        f = "".join(it.split())
        new_items.append(f)
    return new_items






def insertDB(content):
    connection = pymysql.connect(host='127.0.0.1', port=3306, user='root', password='123456', db='us_stock',
                                 charset='utf8mb4', cursorclass=pymysql.cursors.DictCursor)

    cursor = connection.cursor()
    try:

        f_467 = "%s," *467
        cursor.executemany('insert into SP_Nas_ZZG (ZZG_index,{0}) values ({1})'.format(sp_nas_DB,f_467[:-1]), content)
        connection.commit()
        connection.commit()
        connection.close()
        print('向MySQL中添加数据成功！')
    except TypeError :
        pass



if __name__ == '__main__':
    big_list=[]
    mv_l = []
    count_l = []
    zgg120 = 'BABA,TSM,PDD,JD,CHL,BEKE,LFC,NIO,PTR,NTES,SNP,CEO,BIDU,TAL,LU,XPEV,EDU,CHT,LI,ZTO,TME,BGNE,CHA,YUMC,TCOM,FTNT,CHU,IQ,BILI,GSX,GDS,VIPS,HTHT,UMC,ATHM,ASX,WB,ZNH,ZLAB,MLCO,KC,YY,OCFT,CEA,DADA,HNP,FUTU,MNSO,CD,HUYA,ACH,JOBS,DOYU,HCM'
    f_zgg120 =zgg120.split(",")
    for code in f_zgg120:

        url = "http://gu.qq.com/us{0}.OQ/gg".format(code)
        html = call_page(url)

        parse_html(html)
    f_mv_index = sum(count_l)
    big_list.append(str(f_mv_index))
    sp_nas_WEB ='A,AAL,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,ADI,ADM,ADP,ADS,ADSK,AEE,AEP,AES,AFL,AGN,AIG,AIV,AIZ,AJG,AKAM,ALB,ALGN,ALK,ALL_,ALLE,ALXN,AMAT,AMD,AME,AMGN,AMP,AMT,AMZN,ANSS,AON,AOS,APA,APD,APH,APTV,ARE,ASML,ATO,ATVI,AVB,AVGO,AVY,AWK,AXP,AZO,BA,BAC,BAX,BBY,BDX,BEN,BF.B,BIDU,BIIB,BK,BLK,BLL,BMRN,BMY,BR,BRK.B,BSX,BWA,BXP,C,CAG,CAH,CAT,CB,CBOE,CCI,CCL,CDNS,CDW,CE,CERN,CF,CHD,CHKP,CHRW,CHTR,CI,CINF,CL,CLX,CMA,CMCSA,CME,CMG,CMI,CMS,CNC,CNP,COF,COG,COO,COP,COST,COTY,CPB,CPRI,CPRT,CRM,CSCO,CSGP,CSX,CTAS,CTL,CTSH,CTXS,CVS,CVX,CXO,D,DAL,DE,DFS,DG,DGX,DHI,DHR,DIS,DISCA,DISCK,DISH,DLR,DLTR,DOV,DRE,DRI,DTE,DUK,DVA,DVN,DXC,EA,EBAY,ECL,ED,EFX,EIX,EL,EMN,EMR,EOG,EQIX,EQR,ESS,ETFC,ETN,ETR,EW,EXC,EXPD,F,FAST,FB,FCX,FDX,FE,FFIV,FIS,FISV,FITB,FLIR,FLS,FLT,FMC,FOX,FOXA,FRC,FRT,FTI,FTNT,FTV,GD,GE,GILD,GIS,GLW,GM,GOOG,GOOGL,GPC,GPN,GPS,GRMN,GS,GWW,HAL,HAS,HBAN,HBI,HCA,HD,HES,HFC,HIG,HLT,HOG,HOLX,HON,HP,HPE,HPQ,HRB,HRL,HSIC,HST,HSY,HUM,IBM,ICE,IDXX,IEX,IFF,INCY,INFO,INTC,INTU,IP,IPG,IPGP,IR,IRM,ISRG,IT,ITW,IVZ,JBHT,JCI,JD,JKHY,JNJ,JNPR,JPM,JWN,K,KEY,KHC,KIM,KLAC,KMB,KMI,KMX,KO,KR,KSS,KSU,L,LBTYA,LBTYK,LEG,LEN,LH,LKQ,LLY,LMT,LNC,LNT,LOW,LRCX,LUV,LVS,LYB,M,MA,MAA,MAR,MAS,MCD,MCHP,MCK,MCO,MDLZ,MDT,MET,MGM,MHK,MKC,MLM,MMC,MMM,MNST,MO,MOS,MPC,MRK,MRO,MS,MSFT,MSI,MTB,MTD,MU,MXIM,MYL,NBL,NCLH,NDAQ,NEE,NEM,NFLX,NI,NKE,NLSN,NOC,NOV,NOW,NRG,NSC,NTAP,NTES,NTRS,NUE,NVDA,NWL,NWS,NWSA,NXPI,O,OKE,OMC,ORCL,ORLY,OXY,PAYX,PBCT,PCAR,PEG,PEP,PFE,PFG,PG,PGR,PH,PHM,PKG,PKI,PLD,PM,PNC,PNR,PNW,PPG,PPL,PRGO,PRU,PSA,PSX,PVH,PWR,PXD,PYPL,QCOM,RCL,RE,REG,REGN,RF,RHI,RJF,RL,RMD,ROK,ROP,ROST,RSG,RTN,SBAC,SBUX,SCHW,SEE,SHW,SIVB,SJM,SLB,SLG,SNA,SNPS,SO,SPG,SPGI,SRE,STE,STT,STX,STZ,SWK,SWKS,SYF,SYK,SYY,T,TAP,TEL,TFX,TGT,TIF,TJX,TMO,TROW,TRV,TSCO,TSLA,TSN,TWTR,TXN,TXT,UA,UAL,UDR,ULTA,UNH,UNM,UNP,UPS,URI,USB,UTX,V,VAR,VFC,VLO,VMC,VNO,VRSN,VRTX,VTR,VZ,WAB,WAT,WBA,WDAY,WDC,WEC,WFC,WHR,WLTW,WM,WMB,WMT,WRB,WRK,WU,WY,WYNN,XEC,XEL,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBRA,ZION'
    sp_nas_DB ='A,AAL,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,ADI,ADM,ADP,ADS,ADSK,AEE,AEP,AES,AFL,AGN,AIG,AIV,AIZ,AJG,AKAM,ALB,ALGN,ALK,ALL_,ALLE,ALXN,AMAT,AMD,AME,AMGN,AMP,AMT,AMZN,ANSS,AON,AOS,APA,APD,APH,APTV,ARE,ASML,ATO,ATVI,AVB,AVGO,AVY,AWK,AXP,AZO,BA,BAC,BAX,BBY,BDX,BEN,BF_B,BIDU,BIIB,BK,BLK,BLL,BMRN,BMY,BR,BRK_B,BSX,BWA,BXP,C,CAG,CAH,CAT,CB,CBOE,CCI,CCL,CDNS,CDW,CE,CERN,CF,CHD,CHKP,CHRW,CHTR,CI,CINF,CL,CLX,CMA,CMCSA,CME,CMG,CMI,CMS,CNC,CNP,COF,COG,COO,COP,COST,COTY,CPB,CPRI,CPRT,CRM,CSCO,CSGP,CSX,CTAS,CTL,CTSH,CTXS,CVS,CVX,CXO,D,DAL,DE,DFS,DG,DGX,DHI,DHR,DIS,DISCA,DISCK,DISH,DLR,DLTR,DOV,DRE,DRI,DTE,DUK,DVA,DVN,DXC,EA,EBAY,ECL,ED,EFX,EIX,EL,EMN,EMR,EOG,EQIX,EQR,ESS,ETFC,ETN,ETR,EW,EXC,EXPD,F,FAST,FB,FCX,FDX,FE,FFIV,FIS,FISV,FITB,FLIR,FLS,FLT,FMC,FOX,FOXA,FRC,FRT,FTI,FTNT,FTV,GD,GE,GILD,GIS,GLW,GM,GOOG,GOOGL,GPC,GPN,GPS,GRMN,GS,GWW,HAL,HAS,HBAN,HBI,HCA,HD,HES,HFC,HIG,HLT,HOG,HOLX,HON,HP,HPE,HPQ,HRB,HRL,HSIC,HST,HSY,HUM,IBM,ICE,IDXX,IEX,IFF,INCY,INFO,INTC,INTU,IP,IPG,IPGP,IR,IRM,ISRG,IT,ITW,IVZ,JBHT,JCI,JD,JKHY,JNJ,JNPR,JPM,JWN,K,KEY_,KHC,KIM,KLAC,KMB,KMI,KMX,KO,KR,KSS,KSU,L,LBTYA,LBTYK,LEG,LEN,LH,LKQ,LLY,LMT,LNC,LNT,LOW,LRCX,LUV,LVS,LYB,M,MA,MAA,MAR,MAS,MCD,MCHP,MCK,MCO,MDLZ,MDT,MET,MGM,MHK,MKC,MLM,MMC,MMM,MNST,MO,MOS,MPC,MRK,MRO,MS,MSFT,MSI,MTB,MTD,MU,MXIM,MYL,NBL,NCLH,NDAQ,NEE,NEM,NFLX,NI,NKE,NLSN,NOC,NOV,NOW,NRG,NSC,NTAP,NTES,NTRS,NUE,NVDA,NWL,NWS,NWSA,NXPI,O,OKE,OMC,ORCL,ORLY,OXY,PAYX,PBCT,PCAR,PEG,PEP,PFE,PFG,PG,PGR,PH,PHM,PKG,PKI,PLD,PM,PNC,PNR,PNW,PPG,PPL,PRGO,PRU,PSA,PSX,PVH,PWR,PXD,PYPL,QCOM,RCL,RE,REG,REGN,RF,RHI,RJF,RL,RMD,ROK,ROP,ROST,RSG,RTN,SBAC,SBUX,SCHW,SEE,SHW,SIVB,SJM,SLB,SLG,SNA,SNPS,SO,SPG,SPGI,SRE,STE,STT,STX,STZ,SWK,SWKS,SYF,SYK,SYY,T,TAP,TEL,TFX,TGT,TIF,TJX,TMO,TROW,TRV,TSCO,TSLA,TSN,TWTR,TXN,TXT,UA,UAL,UDR,ULTA,UNH,UNM,UNP,UPS,URI,USB,UTX,V,VAR,VFC,VLO,VMC,VNO,VRSN,VRTX,VTR,VZ,WAB,WAT,WBA,WDAY,WDC,WEC,WFC,WHR,WLTW,WM,WMB,WMT,WRB,WRK,WU,WY,WYNN,XEC,XEL,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBRA,ZION'
    f_spNas = sp_nas_WEB.split(",")
    for code in f_spNas:
        url = "http://gu.qq.com/us{0}.OQ/gg".format(code)
        html = call_page(url)
        selector = etree.HTML(html)
        Price = selector.xpath('//*[@id="spFP"]/div[1]/span[1]/text()')
        big_list.append(Price[0])





    ff_l = []
    f_tup = tuple(big_list)
    ff_l.append((f_tup))
    print(ff_l)
    insertDB(ff_l)






 # create table SP_Nas_ZZG(id int not null primary key auto_increment,ZZG_index Float,A FLOAT,AAL FLOAT,AAPL FLOAT,ABBV FLOAT,ABC FLOAT,ABMD FLOAT,ABT FLOAT,ACN FLOAT,ADBE FLOAT,ADI FLOAT,ADM FLOAT,ADP FLOAT,ADS FLOAT,ADSK FLOAT,AEE FLOAT,AEP FLOAT,AES FLOAT,AFL FLOAT,AGN FLOAT,AIG FLOAT,AIV FLOAT,AIZ FLOAT,AJG FLOAT,AKAM FLOAT,ALB FLOAT,ALGN FLOAT,ALK FLOAT,ALL_ FLOAT,ALLE FLOAT,ALXN FLOAT,AMAT FLOAT,AMD FLOAT,AME FLOAT,AMGN FLOAT,AMP FLOAT,AMT FLOAT,AMZN FLOAT,ANSS FLOAT,AON FLOAT,AOS FLOAT,APA FLOAT,APD FLOAT,APH FLOAT,APTV FLOAT,ARE FLOAT,ASML FLOAT,ATO FLOAT,ATVI FLOAT,AVB FLOAT,AVGO FLOAT,AVY FLOAT,AWK FLOAT,AXP FLOAT,AZO FLOAT,BA FLOAT,BAC FLOAT,BAX FLOAT,BBY FLOAT,BDX FLOAT,BEN FLOAT,BF_B FLOAT,BIDU FLOAT,BIIB FLOAT,BK FLOAT,BLK FLOAT,BLL FLOAT,BMRN FLOAT,BMY FLOAT,BR FLOAT,BRK_B FLOAT,BSX FLOAT,BWA FLOAT,BXP FLOAT,C FLOAT,CAG FLOAT,CAH FLOAT,CAT FLOAT,CB FLOAT,CBOE FLOAT,CCI FLOAT,CCL FLOAT,CDNS FLOAT,CDW FLOAT,CE FLOAT,CERN FLOAT,CF FLOAT,CHD FLOAT,CHKP FLOAT,CHRW FLOAT,CHTR FLOAT,CI FLOAT,CINF FLOAT,CL FLOAT,CLX FLOAT,CMA FLOAT,CMCSA FLOAT,CME FLOAT,CMG FLOAT,CMI FLOAT,CMS FLOAT,CNC FLOAT,CNP FLOAT,COF FLOAT,COG FLOAT,COO FLOAT,COP FLOAT,COST FLOAT,COTY FLOAT,CPB FLOAT,CPRI FLOAT,CPRT FLOAT,CRM FLOAT,CSCO FLOAT,CSGP FLOAT,CSX FLOAT,CTAS FLOAT,CTL FLOAT,CTSH FLOAT,CTXS FLOAT,CVS FLOAT,CVX FLOAT,CXO FLOAT,D FLOAT,DAL FLOAT,DE FLOAT,DFS FLOAT,DG FLOAT,DGX FLOAT,DHI FLOAT,DHR FLOAT,DIS FLOAT,DISCA FLOAT,DISCK FLOAT,DISH FLOAT,DLR FLOAT,DLTR FLOAT,DOV FLOAT,DRE FLOAT,DRI FLOAT,DTE FLOAT,DUK FLOAT,DVA FLOAT,DVN FLOAT,DXC FLOAT,EA FLOAT,EBAY FLOAT,ECL FLOAT,ED FLOAT,EFX FLOAT,EIX FLOAT,EL FLOAT,EMN FLOAT,EMR FLOAT,EOG FLOAT,EQIX FLOAT,EQR FLOAT,ESS FLOAT,ETFC FLOAT,ETN FLOAT,ETR FLOAT,EW FLOAT,EXC FLOAT,EXPD FLOAT,F FLOAT,FAST FLOAT,FB FLOAT,FCX FLOAT,FDX FLOAT,FE FLOAT,FFIV FLOAT,FIS FLOAT,FISV FLOAT,FITB FLOAT,FLIR FLOAT,FLS FLOAT,FLT FLOAT,FMC FLOAT,FOX FLOAT,FOXA FLOAT,FRC FLOAT,FRT FLOAT,FTI FLOAT,FTNT FLOAT,FTV FLOAT,GD FLOAT,GE FLOAT,GILD FLOAT,GIS FLOAT,GLW FLOAT,GM FLOAT,GOOG FLOAT,GOOGL FLOAT,GPC FLOAT,GPN FLOAT,GPS FLOAT,GRMN FLOAT,GS FLOAT,GWW FLOAT,HAL FLOAT,HAS FLOAT,HBAN FLOAT,HBI FLOAT,HCA FLOAT,HD FLOAT,HES FLOAT,HFC FLOAT,HIG FLOAT,HLT FLOAT,HOG FLOAT,HOLX FLOAT,HON FLOAT,HP FLOAT,HPE FLOAT,HPQ FLOAT,HRB FLOAT,HRL FLOAT,HSIC FLOAT,HST FLOAT,HSY FLOAT,HUM FLOAT,IBM FLOAT,ICE FLOAT,IDXX FLOAT,IEX FLOAT,IFF FLOAT,INCY FLOAT,INFO FLOAT,INTC FLOAT,INTU FLOAT,IP FLOAT,IPG FLOAT,IPGP FLOAT,IR FLOAT,IRM FLOAT,ISRG FLOAT,IT FLOAT,ITW FLOAT,IVZ FLOAT,JBHT FLOAT,JCI FLOAT,JD FLOAT,JKHY FLOAT,JNJ FLOAT,JNPR FLOAT,JPM FLOAT,JWN FLOAT,K FLOAT,KEY_ FLOAT,KHC FLOAT,KIM FLOAT,KLAC FLOAT,KMB FLOAT,KMI FLOAT,KMX FLOAT,KO FLOAT,KR FLOAT,KSS FLOAT,KSU FLOAT,L FLOAT,LBTYA FLOAT,LBTYK FLOAT,LEG FLOAT,LEN FLOAT,LH FLOAT,LKQ FLOAT,LLY FLOAT,LMT FLOAT,LNC FLOAT,LNT FLOAT,LOW FLOAT,LRCX FLOAT,LUV FLOAT,LVS FLOAT,LYB FLOAT,M FLOAT,MA FLOAT,MAA FLOAT,MAR FLOAT,MAS FLOAT,MCD FLOAT,MCHP FLOAT,MCK FLOAT,MCO FLOAT,MDLZ FLOAT,MDT FLOAT,MET FLOAT,MGM FLOAT,MHK FLOAT,MKC FLOAT,MLM FLOAT,MMC FLOAT,MMM FLOAT,MNST FLOAT,MO FLOAT,MOS FLOAT,MPC FLOAT,MRK FLOAT,MRO FLOAT,MS FLOAT,MSFT FLOAT,MSI FLOAT,MTB FLOAT,MTD FLOAT,MU FLOAT,MXIM FLOAT,MYL FLOAT,NBL FLOAT,NCLH FLOAT,NDAQ FLOAT,NEE FLOAT,NEM FLOAT,NFLX FLOAT,NI FLOAT,NKE FLOAT,NLSN FLOAT,NOC FLOAT,NOV FLOAT,NOW FLOAT,NRG FLOAT,NSC FLOAT,NTAP FLOAT,NTES FLOAT,NTRS FLOAT,NUE FLOAT,NVDA FLOAT,NWL FLOAT,NWS FLOAT,NWSA FLOAT,NXPI FLOAT,O FLOAT,OKE FLOAT,OMC FLOAT,ORCL FLOAT,ORLY FLOAT,OXY FLOAT,PAYX FLOAT,PBCT FLOAT,PCAR FLOAT,PEG FLOAT,PEP FLOAT,PFE FLOAT,PFG FLOAT,PG FLOAT,PGR FLOAT,PH FLOAT,PHM FLOAT,PKG FLOAT,PKI FLOAT,PLD FLOAT,PM FLOAT,PNC FLOAT,PNR FLOAT,PNW FLOAT,PPG FLOAT,PPL FLOAT,PRGO FLOAT,PRU FLOAT,PSA FLOAT,PSX FLOAT,PVH FLOAT,PWR FLOAT,PXD FLOAT,PYPL FLOAT,QCOM FLOAT,RCL FLOAT,RE FLOAT,REG FLOAT,REGN FLOAT,RF FLOAT,RHI FLOAT,RJF FLOAT,RL FLOAT,RMD FLOAT,ROK FLOAT,ROP FLOAT,ROST FLOAT,RSG FLOAT,RTN FLOAT,SBAC FLOAT,SBUX FLOAT,SCHW FLOAT,SEE FLOAT,SHW FLOAT,SIVB FLOAT,SJM FLOAT,SLB FLOAT,SLG FLOAT,SNA FLOAT,SNPS FLOAT,SO FLOAT,SPG FLOAT,SPGI FLOAT,SRE FLOAT,STE FLOAT,STT FLOAT,STX FLOAT,STZ FLOAT,SWK FLOAT,SWKS FLOAT,SYF FLOAT,SYK FLOAT,SYY FLOAT,T FLOAT,TAP FLOAT,TEL FLOAT,TFX FLOAT,TGT FLOAT,TIF FLOAT,TJX FLOAT,TMO FLOAT,TROW FLOAT,TRV FLOAT,TSCO FLOAT,TSLA FLOAT,TSN FLOAT,TWTR FLOAT,TXN FLOAT,TXT FLOAT,UA FLOAT,UAL FLOAT,UDR FLOAT,ULTA FLOAT,UNH FLOAT,UNM FLOAT,UNP FLOAT,UPS FLOAT,URI FLOAT,USB FLOAT,UTX FLOAT,V FLOAT,VAR FLOAT,VFC FLOAT,VLO FLOAT,VMC FLOAT,VNO FLOAT,VRSN FLOAT,VRTX FLOAT,VTR FLOAT,VZ FLOAT,WAB FLOAT,WAT FLOAT,WBA FLOAT,WDAY FLOAT,WDC FLOAT,WEC FLOAT,WFC FLOAT,WHR FLOAT,WLTW FLOAT,WM FLOAT,WMB FLOAT,WMT FLOAT,WRB FLOAT,WRK FLOAT,WU FLOAT,WY FLOAT,WYNN FLOAT,XEC FLOAT,XEL FLOAT,XLNX FLOAT,XOM FLOAT,XRAY FLOAT,XRX FLOAT,XYL FLOAT,YUM FLOAT,ZBRA FLOAT,ZION FLOAT, LastTime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) engine=InnoDB  charset=utf8;






# mei
#*/3 * * * * /home/w/pyenv/bin/python /home/w/SP500_Nasdap100/SP500.py